ALTER TABLE jobs DROP CONSTRAINT IF EXISTS ck_jobs_type;

ALTER TABLE jobs
    ADD CONSTRAINT ck_jobs_type CHECK (type IN (
        'SOURCE_INGESTION', 'QUIZ_GENERATION', 'CHAT_RESPONSE',
        'EXPORT', 'ACCOUNT_DELETION', 'AUTH_EMAIL'
    ));
