package com.genquiz.bk.classroom;
import com.genquiz.bk.common.api.ApiEnvelope; import jakarta.validation.Valid; import java.io.*; import java.time.Instant; import java.util.*;
import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile;
@RestController @RequestMapping("/api/classrooms/{classroomId}")
public class ClassroomCollaborationController {
 private final ClassroomCollaborationService service; public ClassroomCollaborationController(ClassroomCollaborationService service){this.service=service;}
 @GetMapping("/messages") public ApiEnvelope<ClassroomCollaborationDtos.MessagesPage> messages(@PathVariable UUID classroomId,@RequestParam(required=false) Instant before,@RequestParam(required=false) UUID beforeId,@RequestParam(defaultValue="50") int limit,Authentication auth){return ApiEnvelope.success("Lấy tin nhắn thành công.",service.list(ClassroomController.actor(auth),classroomId,before,beforeId,limit));}
 @PostMapping("/messages") public ResponseEntity<ApiEnvelope<ClassroomCollaborationDtos.MessageResponse>> send(@PathVariable UUID classroomId,@Valid @RequestBody ClassroomCollaborationDtos.MessageRequest request,Authentication auth){return ResponseEntity.status(201).body(ApiEnvelope.success("Đã gửi tin nhắn.",service.send(ClassroomController.actor(auth),classroomId,request)));}
 @PatchMapping("/messages/{id}") public ApiEnvelope<ClassroomCollaborationDtos.MessageResponse> edit(@PathVariable UUID classroomId,@PathVariable UUID id,@Valid @RequestBody ClassroomCollaborationDtos.EditMessageRequest request,Authentication auth){return ApiEnvelope.success("Đã sửa tin nhắn.",service.edit(ClassroomController.actor(auth),classroomId,id,request.content()));}
 @DeleteMapping("/messages/{id}") public ResponseEntity<Void> delete(@PathVariable UUID classroomId,@PathVariable UUID id,Authentication auth){service.delete(ClassroomController.actor(auth),classroomId,id);return ResponseEntity.noContent().build();}
 @PostMapping(value="/attachments",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ApiEnvelope<ClassroomCollaborationDtos.AttachmentResponse> upload(@PathVariable UUID classroomId,@RequestPart("file") MultipartFile file,Authentication auth)throws IOException{return ApiEnvelope.success("Đã tải tệp.",service.upload(ClassroomController.actor(auth),classroomId,file));}
 @GetMapping("/attachments/{id}/access") public ApiEnvelope<ClassroomCollaborationDtos.AttachmentAccess> access(@PathVariable UUID classroomId,@PathVariable UUID id,Authentication auth){ClassroomAttachment attachment=service.access(ClassroomController.actor(auth),classroomId,id);return ApiEnvelope.success("Đã cấp quyền tải.",new ClassroomCollaborationDtos.AttachmentAccess(service.signedAccess(attachment),Instant.now().plusSeconds(300)));}
 @GetMapping("/attachments/{id}/content") public ResponseEntity<byte[]> content(@PathVariable UUID classroomId,@PathVariable UUID id,Authentication auth)throws IOException{ClassroomAttachment a=service.access(ClassroomController.actor(auth),classroomId,id);try(InputStream in=service.content(a)){return ResponseEntity.ok().contentType(MediaType.parseMediaType(a.getMediaType())).header(HttpHeaders.CONTENT_DISPOSITION,(a.isImage()?"inline":"attachment")+"; filename*=UTF-8''"+java.net.URLEncoder.encode(a.getOriginalName(),java.nio.charset.StandardCharsets.UTF_8)).body(in.readAllBytes());}}
 @PostMapping("/messages/read") public ResponseEntity<Void> read(@PathVariable UUID classroomId,Authentication auth){service.markRead(ClassroomController.actor(auth),classroomId);return ResponseEntity.noContent().build();}
 @GetMapping("/topic-shares") public ApiEnvelope<List<ClassroomCollaborationDtos.TopicShareResponse>> shares(@PathVariable UUID classroomId,Authentication auth){return ApiEnvelope.success("Lấy tài nguyên thành công.",service.topicShares(ClassroomController.actor(auth),classroomId));}
 @PostMapping("/topic-shares") public ApiEnvelope<ClassroomCollaborationDtos.TopicShareResponse> share(@PathVariable UUID classroomId,@Valid @RequestBody ClassroomCollaborationDtos.TopicShareRequest request,Authentication auth){return ApiEnvelope.success("Đã chia sẻ chủ đề.",service.shareTopic(ClassroomController.actor(auth),classroomId,request));}
 @DeleteMapping("/topic-shares/{id}") public ResponseEntity<Void> revoke(@PathVariable UUID classroomId,@PathVariable UUID id,Authentication auth){service.revokeTopic(ClassroomController.actor(auth),classroomId,id);return ResponseEntity.noContent().build();}
}
